Repository rmescandon/try_git, pull requests merged in 2022-11, with the labels that each got.

#2 NOV-888999: blah blah blah
  .github/workflows/approved.yml
  .github/workflows/checks.yml.bak
  .github/workflows/ci.yaml.bak
Labels: minor release

#5 NOV-444555: Exp/approved actions
  .gitignore
Labels: minor release

#8 NOV-111111: Exp/approved actions
  .github/workflows/release.yaml
Labels: minor release

#9 NOV-888888: update gh actions
  .github/workflows/release.yaml
Labels: feature

#10 NOV-666777: udpate release
  .github/workflows/release.yaml
Labels: not backwards compatible, feature

#11 NOV-555666: more relase changes
  .github/workflows/release.yaml
Labels: feature

#12 NOV-888999: gather all version handling in one step
  .github/workflows/release.yaml
Labels: feature

#13 NOV-898989: Test feat4
  .github/workflows/release.yaml
Labels: feature

#14 NOV-987654: test
  .github/workflows/release.yaml
Labels: feature

#15 NOV-555666: test
  .github/workflows/release.yaml
Labels: feature
